package org.vimal.security.v2.enums;

public enum FeatureFlags {
    MFA,
    MFA_EMAIL,
    MFA_AUTHENTICATOR_APP,
    FORCE_MFA,
    REGISTRATION_ENABLED,
    REGISTRATION_EMAIL_VERIFICATION,
    RESEND_REGISTRATION_EMAIL_VERIFICATION,
    SERVER_UP,
    EMAIL_CHANGE_ENABLED,
    ACCOUNT_DELETION_ALLOWED,
    ALLOW_CREATE_USERS,
    ALLOW_CREATE_USERS_BY_USERS_HAVE_PERMISSION_TO_CREATE_USERS,
    ALLOW_DELETE_USERS,
    ALLOW_DELETE_USERS_BY_USERS_HAVE_PERMISSION_TO_DELETE_USERS,
    ALLOW_HARD_DELETE_USERS,
    ALLOW_HARD_DELETE_USERS_BY_USERS_HAVE_PERMISSION_TO_DELETE_USERS,
    ALLOW_READ_USERS,
    ALLOW_READ_USERS_BY_USERS_HAVE_PERMISSION_TO_READ_USERS,
    ALLOW_UPDATE_USERS,
    ALLOW_UPDATE_USERS_BY_USERS_HAVE_PERMISSION_TO_UPDATE_USERS,
    EMAIL_CONFIRMATION_ON_SELF_ACCOUNT_DELETION
}
